### ISSUE TITLE
尾实体角色

### ISSUE THREAD

**Issue by JiyaoWei** [eXascaleInfolab/HINGE_code#2]
您好，在阅读HINGE的代码时，在model.py文件中发现，模型中没有用到尾实体的角色表示，模型假定头尾实体角色相同，使用头实体角色进行表示关系r，这样难道不会对部分训练数据产生影响吗？比如修改尾实体角色生成得到的负样例。期待您的回信。

**Comment by dingqi** [comment]
HINGE的思路是直接从（h, r, t）三元组去learn，而不像NALP那样从（r_h， h, r_t， t）这样的key-value pairs 去learn。这也是我们claim的重点之一：（h, r, t）三元组的表达 比单纯的key-value pairs 的表达 可以更好建模KG的结构。因为 r_h 和 r_t 是从r凭空创造出来的，我们认为这样做没有意义。
在代码中，我们依然使用了（r_h， h, r_t， t）这样的表达方式（为了和NALP有个更公平的比较）。但是我们丢弃了r_t，也就是说HINGE是从（ h， r_h，t）来learn的，等同于（h, r, t）三元组。我刚才看了一下model代码，里面的变量命名的缺会造成confusion，我让学生去改了，他会改成和paper里面相同的terminology。谢谢你的提醒。
